myblogproject/myblog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('create10/', views.create10, name='create10'),
    path('<int:post_id>/', views.detail, name="detail"),
    path('new/', views.new, name="new"),
    path('<int:post_id>/edit/', views.edit, name='edit'),
    path('<int:post_id>/delete/', views.delete, name="delete"),
    path('<int:post_id>/comments/create/', views.comments_create, name='comments_create'),
    path('<int:post_id>/comments/<int:comment_id>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:post_id>/comments/<int:comment_id>/update/', views.comments_update, name='comments_update'),
    path('<int:post_id>/like/', views.like, name='like'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblogproject/myblogproject/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls import url 


urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('myblog.urls')),
    path('accounts/', include('allauth.urls')),
]

myblogproject/myblog/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    pub_date = models.DateTimeField('date published')
    body = models.TextField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:20]


class Comment(models.Model):
    post = models.ForeignKey('myblog.Post', on_delete = models.CASCADE)
    content = models.TextField()

    def __str__(self):
        return self.content

myblogproject/myblog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'body', 'image')

myblogproject/myblog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment
from faker import Faker 
from django.utils import timezone 
from .forms import PostForm

# Create your views here.

def home(request):
    posts = Post.objects
    return render(request, 'home.html', {'posts':posts})

def create10(request):
    ifake = Faker()
    for i in range(10):
        post = Post()
        post.title = ifake.name()
        post.body = ifake.sentence()
        post.pub_date = timezone.datetime.now()
        post.save()
    return redirect('/')

def detail(request, post_id):
    post_detail = get_object_or_404(Post, pk=post_id)
    return render(request, 'detail.html', {'post':post_detail})

#def new(request):
#   form = PostForm()
#   return render(request, 'new.html', {'form': form})

def new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.pub_date = timezone.now()
            post.save()
            return redirect('/' + str(post.id))
    else:
        form = PostForm()
        return render(request, 'new.html', {'form': form})

def edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.pub_date = timezone.now()
            post.save()
            return redirect('/' + str(post.id))
    else:
        form = PostForm(instance=post)
    return render(request, 'new.html', {'form': form})

def delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect('/')

def comments_create(request, post_id):
    #댓글을 달 게시물에 대한 정보 가져오기
    post = Post.objects.get(pk=post_id)
    #form 태그에서 넘어온 댓글 내용 가져오기
    content = request.POST.get('content')
 
    #댓글 생성 및 저장 
    comment = Comment(post=post, content=content)
    comment.save()
    
    #댓글 생성후, 디테일 페이지로 redirect시킴
    return redirect('/' + str(post.id))

def comments_delete(request, post_id, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    comment.delete()
    
    return redirect('/'+str(post_id))

def comments_update(request, post_id, comment_id):
    post = get_object_or_404(Post, pk=post_id)
    comment = get_object_or_404(Comment, id=comment_id)

    if request.method == 'POST':
        comment.content = request.POST.get('content')
        comment.save()
        return redirect('/'+str(post_id))
    
    else:
        return render(request, 'comments_update.html', {'post':post, 'comment':comment})
    
def like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    
    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
    else:
        post.like_users.add(request.user)
    
    return redirect('/' + str(post.id))
    

myblogproject/myblog/templates/comments_update.html
<!-- Single Comment -->
{% for comments in post.comment_set.all %}
{% if comments.id != comment.id %}
<div class="media mb-4">
  <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
  <div class="media-body">            
    <h5 class="mt-0">anonymous</h5>
    {{comment}} 
    <div align="right">
      <a href="{%url 'comments_update' post.id comment.id %}" class="btn btn-primary my-2">Edit</a>
      <a href="{%url 'comments_delete' post.id comment.id %}" class="btn btn-primary my-2">Delete</a>
    </div>
  </div>
</div>
{% else %}
<div class="card-body">
    <form action="{% url 'comments_update' post.pk comment.id %}" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <textarea class="form-control" rows="3" name="content">{{comment.content}}</textarea>
      </div>
      <div align="right">
      <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
</div>
{% endif %}
{% endfor %}

myblogproject/myblog/templates/detail.html
{% extends 'base.html' %}


{% block content %}
  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{ post.title }}</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">Sejin</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{ post.pub_date }}</p>

        <hr>

        <!-- Preview Image -->
        {% if post.image != '' %}
        <img src="{{ post.image.url }}" height= "500" alt=" Card image cap">    

        {% else %}
        <svg width="100%" height="500" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">No image</text></svg>
                    
        {% endif %}

        <hr>

        <!-- Post Content -->
        <p class="lead">{{post.body}}</p>

        <hr>

        <div align="right">
           
            <a href="{% url 'edit' post.id %}" class="btn btn-primary my-2">Edit</a>
            <a href="{%url 'delete' post.id %}" class="btn btn-primary my-2">Delete</a>
            
          </div>

        <!-- Comments Form -->
  
         <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
              <form action="{% url 'comments_create' post.pk %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <textarea class="form-control" rows="3" name="content"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>

        <!-- Single Comment -->
        {% for comment in post.comment_set.all %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">            
            <h5 class="mt-0">anonymous</h5>
            {{comment}} 
            <div align="right">
              <a href="{%url 'comments_update' post.id comment.id %}" class="btn btn-primary my-2">Edit</a>
              <a href="{%url 'comments_delete' post.id comment.id %}" class="btn btn-primary my-2">Delete</a>
            </div>
          </div>
        </div>
        {% endfor %}

        

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">열심히들</a>
                  </li>
                  <li>
                    <a href="#">하고</a>
                  </li>
                  <li>
                    <a href="#">계신가요</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">어려운 부분이</a>
                  </li>
                  <li>
                    <a href="#">있다면 바로</a>
                  </li>
                  <li>
                    <a href="#">질문해주세요.</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">심심해서 남겨두는 Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  {% endblock%}

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
    <!-- Like-->
    <div class="card my-4">
      <div class="card-header">
        {% if user.is_authenticated %}
          {% if user in post.like_users.all %}
            <a href="{% url 'like' post.id %}"><i class="fas fa-heart"></i></a>
          {% else %}
            <a href="{% url 'like' post.id %}"><i class="far fa-heart"></i></a>
          {% endif %}
            <!--like user count-->
            {{ post.like_users.count }}명이 좋아합니다.<br><br>
                
        {% else %}
        <i class="far fa-heart"></i> {{ post.like_users.count }}명이 좋아합니다.
        <br>좋아요를 누르려면 로그인이 필요합니다.
          
        {% endif %}

        {% for likeuser in post.like_users.all %}
          {{likeuser.username}}
        {% endfor %}
      </div>
    </div>

myblogproject/myblog/templates/home.html
{% extends 'base.html' %}

{% load socialaccount %}
{% providers_media_js %}


{% block content %}
 
        <section class="jumbotron text-center">
            <div class="container">
                <h1>Sejin's Blog</h1>
                <p class="lead text-muted">Thank you for coming my blog:) I hope you have a great day!</p>
                <p>
                    <br>
                   
                    <a href="{%url 'new' %}" class="btn btn-primary my-2">Add Post</a>
                    <a href = "{%url 'create10' %}" class = "btn btn-secondary my-2">create 10 Post</a>
                </p>
            </div>
        </section>
        
        <div class="album py-5 bg-light">
            <div class="container">
        
                <div class="row">
                    {% for post in posts.all %}
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            {% if post.image != '' %} <!-- 이미지가 비어있지 않으면-->
                            <img class="card-img-top" src="{{ post.image.url }}" height= "225" alt=" Card image cap">    
        
                            {% else %}<!-- 이미지가 비어있다면-->
                            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">No image</text></svg>
                            
                            {% endif %}
        
                            <div class="card-body">
                                <h4>{{ post.title }}</h4>
                                <p class="card-text">{{ post.summary }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    

                                        <div class="btn-group">
                                            <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'detail' post.id %}';"> View</button>
                                            <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'delete' post.id %}';">Del</button> 
                                    
                            
                                    </div>
                                    <small class="text-muted">{{ post.pub_date }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        
        
{% endblock%}

<a href="/accounts/signup">회원가입</a><br>

{% if user.is_authenticated %}
<a href="/accounts/logout">로그아웃</a><br>
{{user.username}} 님이 로그인 중

{% else %}
<a href="/accounts/login">Login</a>
<a href="{% provider_login_url 'google' %}">Login with google</a><br>

{% endif %}

myblogproject/myblog/templates/new.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
    <h1>New post</h1>
    <br>
    <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

{% endblock%}

myblogproject/myblogproject/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Sejin's blog</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.5/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
  </head>
  <body>
    <header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the blog.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex bd-highlight">
        <div class="mr-auto p-2 bd-highlight">
            <a href="{% url 'home' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                    stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2"
                    viewBox="0 0 24 24" focusable="false">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
                    <circle cx="12" cy="13" r="4" /></svg>
                <strong>Mulgyeol's Blog</strong>
            </a>
        </div>
        
        <div class="p-2 bd-highlight">
            {% if user.is_authenticated %}
                <div class="navbar-text">{{user.username}}님이 로그인 중입니다.</div>
            {% endif %}
        </div>

        <div class="p-2 bd-highlight">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
            aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        </div>
    </div>
</div>

</header>

<main role="main">
    {% block content %}
    {% endblock %}
    </main>

    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
                <br>
                2020.08.25
            </p>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    <script src="/docs/4.5/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf"
        crossorigin="anonymous"></script>
</body>
</html>